import { useState, useRef } from "react";
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Cell } from "recharts";
import { useSources } from "@/hooks/use-sources";
import { ChevronDown, ArrowRight, X, ExternalLink } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

// ─── SCENARIO DATA ───────────────────────────────────────────────────────────

interface Scenario {
  id: string;
  label: string;
  sentence: string;
  clarifying: string;
  energyWh: number;
  waterMl: number;
  chartLabel: string;
}

const SCENARIOS: Scenario[] = [
  {
    id: "short-chat",
    label: "short chat",
    sentence: "To **send a short chat message**, roughly **0.003 Wh** of energy [about **1 second of an LED bulb**] and **10 mL** of water [about **2 teaspoons worth**] were consumed.",
    clarifying: "Estimated for a single short prompt (1–10 words) sent to an AI assistant. Based on Luccioni et al. (2023) measurements of text-generation inference at ~0.0003 kWh per 1,000 tokens, and Goldman Sachs (2024) estimates. Actual energy and water use vary by model size, data center location, and cooling method.",
    energyWh: 0.003,
    waterMl: 10,
    chartLabel: "Short Chat",
  },
  {
    id: "long-chat",
    label: "long chat",
    sentence: "To **have a long AI conversation**, roughly **0.3 Wh** of energy [about **22 minutes of an LED bulb**] and **500 mL** of water [about **5 handwashes worth**] were consumed.",
    clarifying: "Estimated for a 20–50 message back-and-forth conversation with an AI assistant. Li et al. (2023) directly estimated ~500 mL of water per conversation of this length. Energy is scaled from per-query estimates, accounting for growing context windows in later turns. Both figures are mid-range estimates with significant uncertainty.",
    energyWh: 0.3,
    waterMl: 500,
    chartLabel: "Long Chat",
  },
  {
    id: "image",
    label: "image",
    sentence: "To **generate an AI image**, roughly **2.4 Wh** of energy [about **3 mins of watching Netflix**] and **200 mL** of water [about **2 handwashes worth**] were consumed.",
    clarifying: "Estimated for a single image generated by a diffusion model (e.g. Stable Diffusion, Midjourney, DALL·E). Luccioni et al. (2023) directly measured image generation at ~2.9 Wh per image. Water is extrapolated from energy using Li et al. (2023) methodology. Values depend heavily on inference steps and GPU used.",
    energyWh: 2.4,
    waterMl: 200,
    chartLabel: "Image Gen",
  },
  {
    id: "video",
    label: "video",
    sentence: "To **generate a short AI video**, roughly **944 Wh** of energy [about **20 hours of watching Netflix**] and **20 L** of water [about **182 handwashes worth**] were consumed.",
    clarifying: "Estimated for a 5–15 second video clip generated by an AI model (e.g. Sora, Runway, Pika). Based on Fernandez et al. (2025, ACL) direct measurements of video generation — among the most energy-intensive AI operations. This is roughly equivalent to leaving a laptop running for 9 hours straight.",
    energyWh: 944,
    waterMl: 20000,
    chartLabel: "Video Gen",
  },
  {
    id: "coding",
    label: "coding",
    sentence: "To **get an AI code suggestion**, roughly **0.001 Wh** of energy [about **less than 1 second of an LED bulb**] and **3 mL** of water [about **less than a teaspoon**] were consumed.",
    clarifying: "Estimated for a single inline code completion or autocomplete suggestion (e.g. GitHub Copilot, Cursor). These short-context inference calls are among the lowest-impact AI tasks. However, developers may generate hundreds of suggestions per session — cumulative use adds up quickly.",
    energyWh: 0.001,
    waterMl: 3,
    chartLabel: "Code Suggest",
  },
  {
    id: "app-build",
    label: "app build",
    sentence: "To **vibe code** a **simple app**, roughly **50 Wh** of energy [about **60 mins of watching Netflix**] and **2.5 L** of water [about **23 handwashes worth**] were consumed.",
    clarifying: "Estimated for a 1–2 hour session of AI-assisted app building (vibe coding), involving many back-and-forth exchanges, code generation, debugging, and iteration. Derived by scaling per-query estimates across a realistic session with larger code context windows. This is a rough mid-range estimate — sessions vary widely by model and complexity.",
    energyWh: 50,
    waterMl: 2500,
    chartLabel: "App Build",
  },
  {
    id: "training-llm",
    label: "training LLM",
    sentence: "To **train a large language model**, roughly **1.287 GWh** of energy [about **122 homes powered for a year**] and **700,000 L** of water [about **1,750 bathtubs full**] were consumed.",
    clarifying: "Estimated for training a GPT-3 scale large language model (175B parameters). Based on Strubell et al. (2019) and subsequent analyses. Frontier models like GPT-4 are likely orders of magnitude higher — but companies do not disclose this. This figure represents what we can verify from open-source model documentation.",
    energyWh: 1287000000,
    waterMl: 700000000,
    chartLabel: "Train LLM",
  },
  {
    id: "audio-transcript",
    label: "audio transcript",
    sentence: "To **transcribe a minute of audio**, roughly **0.002 Wh** of energy [about **1 second of an LED bulb**] and **2 mL** of water [about **40 drops**] were consumed.",
    clarifying: "Estimated for transcribing 1 minute of audio using an AI speech-to-text model (e.g. Whisper, Google STT). Based on scaled estimates from Luccioni et al. (2023). Data on audio transcription energy use is limited — this is a low-confidence estimate. Water use extrapolated from energy via Li et al. (2023) methodology.",
    energyWh: 0.002,
    waterMl: 2,
    chartLabel: "Audio Transcript",
  },
];

// ─── OFFSET ACTIONS ──────────────────────────────────────────────────────────

const ENERGY_OFFSETS = [
  { id: "light", label: "Turn off a 10W LED bulb", unitLabel: "hours", whPerUnit: 10 },
  { id: "ac", label: "Skip 1 hour of air conditioning", unitLabel: "hours", whPerUnit: 3500 },
  { id: "laundry", label: "Air-dry laundry instead of tumble dryer", unitLabel: "loads", whPerUnit: 2400 },
  { id: "walk", label: "Walk instead of drive", unitLabel: "km", whPerUnit: 200 },
  { id: "laptop", label: "Turn off a laptop", unitLabel: "hours", whPerUnit: 45 },
];

const WATER_OFFSETS = [
  { id: "shower", label: "Take a shorter shower", unitLabel: "minutes shorter", mlPerUnit: 8000 },
  { id: "flush", label: "Skip a toilet flush", unitLabel: "flushes", mlPerUnit: 9000 },
  { id: "dishwasher", label: "Run dishwasher vs. hand-washing dishes", unitLabel: "loads", mlPerUnit: 50000 },
  { id: "tap", label: "Turn off tap while brushing teeth", unitLabel: "times", mlPerUnit: 2000 },
  { id: "garden", label: "Water garden in the evening vs. midday", unitLabel: "sessions", mlPerUnit: 3000 },
];

const TRUSTED_LINKS = [
  { name: "Arcadia", url: "https://arcadia.com", desc: "Switch your home to clean energy" },
  { name: "Wren", url: "https://www.wren.co", desc: "Monthly carbon offset subscription" },
  { name: "TerraPass", url: "https://www.terrapass.com", desc: "Carbon offsets and renewable energy credits" },
  { name: "EPA WaterSense", url: "https://www.epa.gov/watersense", desc: "Water efficiency products and tips" },
  { name: "Water Calculator", url: "https://www.watercalculator.org", desc: "Calculate your personal water footprint" },
];

// ─── KNOWLEDGE GAPS ──────────────────────────────────────────────────────────

const GAPS = [
  {
    title: "Proprietary Training Data",
    body: "Major AI companies rarely disclose the full megawatt usage or GPU-hours required to train their foundation models. Training energy is orders of magnitude higher than inference, but we only have solid estimates for open-source models like BLOOM or LLaMA. Numbers for GPT-4, Claude, and Gemini remain undisclosed.",
  },
  {
    title: "Evaporative Cooling Variability",
    body: "Water usage estimates depend heavily on where the data center is located. A server in Ireland might use free air cooling (near 0 mL water), while the same query routed to Arizona might require extensive evaporative cooling. Operators don't disclose which servers handle which requests.",
  },
  {
    title: "Hardware Lifecycle Footprint",
    body: "Current estimates focus on operational energy use (Scope 2 emissions). They rarely factor in the embodied carbon (Scope 3) of manufacturing GPUs, networking equipment, and the concrete for data centers — which can represent 50–80% of total lifecycle impact.",
  },
  {
    title: "Model Version Opacity",
    body: "Companies continuously update their models without versioned energy disclosures. A 'ChatGPT query' in 2023 may have very different resource use from one in 2025 due to model optimizations, new hardware, and architectural changes. Longitudinal comparison is nearly impossible.",
  },
  {
    title: "Workload Routing Opacity",
    body: "When you send a query, you don't know which data center processes it, which hardware tier runs it, or what the local grid's carbon intensity is. All estimates here represent population averages, masking significant real-world variation.",
  },
];

// ─── CHART HELPERS ───────────────────────────────────────────────────────────

type ChartMetric = "energy" | "water";
type ChartUnit = "raw" | "equiv1" | "equiv2";

function getChartValue(s: Scenario, metric: ChartMetric, unit: ChartUnit): number {
  if (metric === "energy") {
    const wh = s.energyWh;
    if (unit === "raw") return wh;
    if (unit === "equiv1") return wh / 0.8;
    if (unit === "equiv2") return wh / 10;
  } else {
    const ml = s.waterMl;
    if (unit === "raw") return ml;
    if (unit === "equiv1") return ml / 110;
    if (unit === "equiv2") return ml / 500;
  }
  return 0;
}

function getUnitLabel(metric: ChartMetric, unit: ChartUnit): string {
  if (metric === "energy") {
    if (unit === "raw") return "Wh";
    if (unit === "equiv1") return "mins of Netflix";
    if (unit === "equiv2") return "hrs of LED bulb";
  } else {
    if (unit === "raw") return "mL";
    if (unit === "equiv1") return "handwashes";
    if (unit === "equiv2") return "500 mL bottles";
  }
  return "";
}

function fmtVal(v: number): string {
  if (v === 0) return "0";
  if (v < 0.001) return v.toExponential(1);
  if (v < 1) return v.toFixed(3);
  if (v < 1000) return Math.round(v * 10) / 10 + "";
  if (v < 1000000) return (v / 1000).toFixed(1) + "k";
  if (v < 1000000000) return (v / 1000000).toFixed(1) + "M";
  return (v / 1000000000).toFixed(2) + "B";
}

function fmtOffset(amount: number, unitLabel: string): string {
  if (amount < 0.01) return `less than 1 ${unitLabel.split(" ")[0]}`;
  if (amount < 1) return `${(amount).toFixed(2)} ${unitLabel}`;
  if (amount < 100) return `${Math.round(amount * 10) / 10} ${unitLabel}`;
  return `${Math.round(amount).toLocaleString()} ${unitLabel}`;
}

function fmtEnergy(wh: number): string {
  if (wh < 1) return `${(wh * 1000).toFixed(1)} mWh`;
  if (wh >= 1000000000) return `${(wh / 1000000000).toFixed(3)} GWh`;
  if (wh >= 1000000) return `${(wh / 1000000).toFixed(1)} MWh`;
  if (wh >= 1000) return `${(wh / 1000).toFixed(1)} kWh`;
  return `${wh} Wh`;
}

function fmtWater(ml: number): string {
  if (ml < 1000) return `${ml} mL`;
  if (ml >= 1000000) return `${(ml / 1000000).toFixed(0).toLocaleString()} kL`;
  return `${(ml / 1000).toFixed(1)} L`;
}

// ─── SENTENCE RENDERER ───────────────────────────────────────────────────────

function SentenceText({ sentence }: { sentence: string }) {
  const parts = sentence.split(/(\*\*[^*]+\*\*)/g).map((p) =>
    p.startsWith("**") && p.endsWith("**")
      ? { text: p.slice(2, -2), fill: true }
      : { text: p, fill: false }
  );
  return (
    <p
      className="text-[1.65rem] leading-[2.1] text-black max-w-xl text-center"
      style={{ fontFamily: "'Instrument Serif', serif", fontWeight: 400 }}
    >
      {parts.map((p, i) =>
        p.fill ? (
          <span
            key={i}
            className="border-b border-black/70 pb-[1px]"
            style={{ borderBottomWidth: "1.5px" }}
          >
            {p.text}
          </span>
        ) : (
          <span key={i}>{p.text}</span>
        )
      )}
    </p>
  );
}

// ─── MODAL WRAPPER ───────────────────────────────────────────────────────────

function Modal({ onClose, children }: { onClose: () => void; children: React.ReactNode }) {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-6">
      <motion.div
        className="absolute inset-0 bg-black/15 backdrop-blur-sm"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        onClick={onClose}
      />
      <motion.div
        className="relative bg-white rounded-2xl border border-gray-200 shadow-2xl max-w-2xl w-full max-h-[80vh] overflow-hidden flex flex-col z-10"
        initial={{ scale: 0.96, opacity: 0, y: 8 }}
        animate={{ scale: 1, opacity: 1, y: 0 }}
        exit={{ scale: 0.96, opacity: 0, y: 8 }}
        transition={{ type: "spring", damping: 28, stiffness: 400 }}
      >
        <button
          onClick={onClose}
          className="absolute top-4 right-4 p-2 rounded-full hover:bg-gray-100 transition-colors z-10"
        >
          <X size={16} className="text-gray-400" />
        </button>
        {children}
      </motion.div>
    </div>
  );
}

// ─── SOURCES MODAL ───────────────────────────────────────────────────────────

function SourcesModal() {
  const { data: sources, isLoading } = useSources();
  return (
    <>
      <div className="px-8 pt-8 pb-5 border-b border-gray-100 shrink-0">
        <h2 className="text-lg font-semibold text-black">Sources</h2>
        <p className="text-xs text-gray-400 italic mt-1 leading-relaxed">
          We believe in showing our work. All data is sourced from published research, government reports, and industry analyses.
        </p>
      </div>
      <div className="overflow-y-auto flex-1 px-8 py-6 flex flex-col gap-5">
        {isLoading && <p className="text-xs text-gray-400 italic">Loading sources…</p>}
        {(sources || []).map((s) => (
          <div key={s.id} className="border-b border-gray-100 pb-5 last:border-0">
            <div className="flex items-start justify-between gap-4">
              <div className="flex-1 min-w-0">
                <p className="font-medium text-black text-sm leading-snug">{s.title}</p>
                <p className="text-xs text-gray-400 mt-0.5">
                  {s.institution} · {s.year}
                </p>
              </div>
              <a
                href={s.url}
                target="_blank"
                rel="noopener noreferrer"
                className="shrink-0 text-gray-300 hover:text-black transition-colors mt-0.5"
              >
                <ExternalLink size={13} />
              </a>
            </div>
            {s.keyFindings && (
              <p className="text-xs text-gray-500 italic mt-2 leading-relaxed line-clamp-3">
                {s.keyFindings.slice(0, 220)}{s.keyFindings.length > 220 ? "…" : ""}
              </p>
            )}
          </div>
        ))}
      </div>
    </>
  );
}

// ─── GAPS MODAL ──────────────────────────────────────────────────────────────

function GapsModal() {
  return (
    <>
      <div className="px-8 pt-8 pb-5 border-b border-gray-100 shrink-0">
        <h2 className="text-lg font-semibold text-black">Knowledge Gaps</h2>
        <p className="text-xs text-gray-400 italic mt-1 leading-relaxed">
          Honesty means acknowledging what we don't know. Much of this data is hidden behind corporate NDAs and limited public disclosure.
        </p>
      </div>
      <div className="overflow-y-auto flex-1 px-8 py-6 flex flex-col gap-5">
        {GAPS.map((gap, i) => (
          <div key={i} className="border-b border-gray-100 pb-5 last:border-0">
            <p className="text-sm font-semibold text-black mb-1">{gap.title}</p>
            <p className="text-sm text-gray-500 leading-relaxed font-light">{gap.body}</p>
          </div>
        ))}
        <div className="rounded-xl border border-gray-200 bg-gray-50 p-5 mt-1">
          <p className="text-sm font-semibold text-black mb-1">Want to contribute?</p>
          <p className="text-xs text-gray-500 leading-relaxed font-light mb-3">
            If you're a researcher or have access to credible infrastructure data, you can help fill these gaps.
          </p>
          <a
            href="mailto:hello@theaitab.com?subject=Resource submission"
            className="inline-flex items-center gap-1.5 text-xs font-medium text-black underline underline-offset-2 hover:opacity-60 transition-opacity"
          >
            Submit a resource <ExternalLink size={11} />
          </a>
        </div>
      </div>
    </>
  );
}

// ─── GUILT PANEL ─────────────────────────────────────────────────────────────

function GuiltPanel({ scenario, onClose }: { scenario: Scenario; onClose: () => void }) {
  const [energyOffset, setEnergyOffset] = useState(ENERGY_OFFSETS[0].id);
  const [waterOffset, setWaterOffset] = useState(WATER_OFFSETS[0].id);

  const ea = ENERGY_OFFSETS.find((a) => a.id === energyOffset)!;
  const wa = WATER_OFFSETS.find((a) => a.id === waterOffset)!;

  const eAmount = scenario.energyWh / ea.whPerUnit;
  const wAmount = scenario.waterMl / wa.mlPerUnit;

  return (
    <>
      <div className="fixed inset-0 z-40" onClick={onClose} />
      <motion.div
        className="fixed right-0 top-0 h-full z-50 w-[380px] bg-white border-l-2 border-[#9ecfaf] shadow-2xl overflow-y-auto"
        initial={{ x: "100%" }}
        animate={{ x: 0 }}
        exit={{ x: "100%" }}
        transition={{ type: "spring", damping: 26, stiffness: 320 }}
      >
        <div className="p-8 flex flex-col gap-7">
          <div className="flex items-start justify-between gap-3">
            <div>
              <h2 className="text-base font-semibold text-black leading-snug">How to remove the guilt</h2>
              <p className="text-xs text-gray-400 italic mt-1 leading-relaxed">
                Offset the resources used by making these changes elsewhere in your day.
              </p>
            </div>
            <button onClick={onClose} className="p-1.5 rounded-full hover:bg-gray-100 transition-colors shrink-0">
              <X size={15} className="text-gray-400" />
            </button>
          </div>

          {/* Energy */}
          <div className="rounded-2xl border-2 border-[#9ecfaf] bg-[#f3faf6] p-5">
            <p className="text-[10px] text-gray-400 uppercase tracking-[0.12em] font-medium mb-3">Energy offset</p>
            <select
              value={energyOffset}
              onChange={(e) => setEnergyOffset(e.target.value)}
              className="w-full text-sm border border-gray-200 rounded-lg px-3 py-2 bg-white text-black focus:outline-none focus:border-[#9ecfaf] mb-4 font-light"
            >
              {ENERGY_OFFSETS.map((a) => (
                <option key={a.id} value={a.id}>{a.label}</option>
              ))}
            </select>
            <p className="text-sm text-black leading-snug font-light">
              <span className="font-bold">{fmtOffset(eAmount, ea.unitLabel)}</span>{" "}
              to offset <span className="font-medium">{fmtEnergy(scenario.energyWh)}</span>
            </p>
          </div>

          {/* Water */}
          <div className="rounded-2xl border-2 border-[#9ecfaf] bg-[#f3faf6] p-5">
            <p className="text-[10px] text-gray-400 uppercase tracking-[0.12em] font-medium mb-3">Water offset</p>
            <select
              value={waterOffset}
              onChange={(e) => setWaterOffset(e.target.value)}
              className="w-full text-sm border border-gray-200 rounded-lg px-3 py-2 bg-white text-black focus:outline-none focus:border-[#9ecfaf] mb-4 font-light"
            >
              {WATER_OFFSETS.map((a) => (
                <option key={a.id} value={a.id}>{a.label}</option>
              ))}
            </select>
            <p className="text-sm text-black leading-snug font-light">
              <span className="font-bold">{fmtOffset(wAmount, wa.unitLabel)}</span>{" "}
              to offset <span className="font-medium">{fmtWater(scenario.waterMl)}</span>
            </p>
          </div>

          {/* Trusted platforms */}
          <div>
            <p className="text-[10px] text-gray-400 uppercase tracking-[0.12em] font-medium mb-3">Trusted platforms</p>
            <div className="flex flex-col gap-2">
              {TRUSTED_LINKS.map((link) => (
                <a
                  key={link.url}
                  href={link.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center justify-between gap-3 border border-gray-200 rounded-xl px-4 py-3 hover:border-gray-400 transition-colors group"
                >
                  <div>
                    <p className="text-xs font-medium text-black">{link.name}</p>
                    <p className="text-[11px] text-gray-400 font-light">{link.desc}</p>
                  </div>
                  <ExternalLink size={12} className="text-gray-300 group-hover:text-gray-500 transition-colors shrink-0" />
                </a>
              ))}
            </div>
          </div>
        </div>
      </motion.div>
    </>
  );
}

// ─── CHART TOOLTIP ───────────────────────────────────────────────────────────

function ChartTooltip({ active, payload, label, unitLabel }: any) {
  if (!active || !payload?.length) return null;
  return (
    <div className="bg-white border border-gray-200 rounded-lg px-4 py-2.5 shadow-lg">
      <p className="text-xs font-semibold text-black">{label}</p>
      <p className="text-xs text-gray-500 font-light">{fmtVal(payload[0].value)} {unitLabel}</p>
    </div>
  );
}

// ─── MAIN ────────────────────────────────────────────────────────────────────

export default function Home() {
  const [selectedId, setSelectedId] = useState("app-build");
  const [showSources, setShowSources] = useState(false);
  const [showGaps, setShowGaps] = useState(false);
  const [showGuilt, setShowGuilt] = useState(false);
  const [chartMetric, setChartMetric] = useState<ChartMetric>("energy");
  const [chartUnit, setChartUnit] = useState<ChartUnit>("raw");
  const [excludeTraining, setExcludeTraining] = useState(true);

  const chartsRef = useRef<HTMLDivElement>(null);
  const scenario = SCENARIOS.find((s) => s.id === selectedId) ?? SCENARIOS[5];

  const chartData = SCENARIOS.filter((s) => !excludeTraining || s.id !== "training-llm").map((s) => ({
    name: s.chartLabel,
    value: getChartValue(s, chartMetric, chartUnit),
    id: s.id,
  }));

  const unitLabel = getUnitLabel(chartMetric, chartUnit);

  return (
    <div className="min-h-screen bg-white" style={{ fontFamily: "'Jost', sans-serif" }}>

      {/* ─── HERO SCREEN ─────────────────────────────────────────────── */}
      <div className="h-screen flex relative overflow-hidden">

        {/* LEFT — scenario pill column */}
        <div className="flex flex-col gap-2.5 justify-center pl-10 pr-6 py-12 shrink-0">
          {SCENARIOS.map((s) => (
            <button
              key={s.id}
              onClick={() => setSelectedId(s.id)}
              className={[
                "px-5 py-2 rounded-full text-sm transition-all duration-150 text-left whitespace-nowrap",
                selectedId === s.id
                  ? "bg-black text-white font-medium"
                  : "border border-gray-300 text-gray-400 hover:border-gray-500 hover:text-gray-600 font-light",
              ].join(" ")}
            >
              {s.label}
            </button>
          ))}
        </div>

        {/* CENTER — sentence + clarifying */}
        <div className="flex-1 flex flex-col items-center justify-center px-10 py-16">
          <AnimatePresence mode="wait">
            <motion.div
              key={selectedId}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -6 }}
              transition={{ duration: 0.25, ease: "easeOut" }}
              className="flex flex-col items-center gap-7 max-w-xl"
            >
              <SentenceText sentence={scenario.sentence} />
              <p className="text-[11px] text-gray-400 font-light leading-relaxed max-w-md text-center italic">
                {scenario.clarifying}
              </p>
            </motion.div>
          </AnimatePresence>
        </div>

        {/* RIGHT — guilt indicator */}
        <div className="flex flex-col justify-center pl-4 pr-8 py-12 shrink-0 min-w-[150px]">
          <AnimatePresence>
            {!showGuilt && (
              <motion.button
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                onClick={() => setShowGuilt(true)}
                className="flex items-center gap-2 text-gray-400 hover:text-black transition-colors group text-xs font-light text-left"
              >
                <span className="leading-snug">how to remove the guilt</span>
                <ArrowRight size={13} className="shrink-0 group-hover:translate-x-0.5 transition-transform" />
              </motion.button>
            )}
          </AnimatePresence>
        </div>

        {/* BOTTOM BAR */}
        <div className="absolute bottom-0 left-0 right-0 flex items-end justify-between px-10 pb-8">
          {/* Sources + Gaps */}
          <div className="flex items-center gap-4">
            <button
              onClick={() => setShowSources(true)}
              className="text-[11px] text-gray-400 hover:text-black transition-colors font-light italic underline underline-offset-2"
            >
              sources
            </button>
            <span className="text-gray-200 select-none">·</span>
            <button
              onClick={() => setShowGaps(true)}
              className="text-[11px] text-gray-400 hover:text-black transition-colors font-light italic underline underline-offset-2"
            >
              knowledge gaps
            </button>
          </div>

          {/* Compare tasks */}
          <button
            onClick={() => chartsRef.current?.scrollIntoView({ behavior: "smooth" })}
            className="flex flex-col items-center gap-0.5 text-gray-400 hover:text-black transition-colors group"
          >
            <span className="text-[11px] font-light tracking-wide">compare tasks</span>
            <ChevronDown size={13} className="group-hover:translate-y-0.5 transition-transform" />
            <ChevronDown size={13} className="-mt-2.5 opacity-30 group-hover:translate-y-0.5 transition-transform" />
          </button>

          {/* Disclaimer */}
          <p className="text-[10px] text-gray-300 italic font-light max-w-[220px] text-right leading-relaxed">
            Mid-range estimates based on published research. Actual values vary by model, data center, and region.
          </p>
        </div>
      </div>

      {/* ─── COMPARE TASKS SECTION ───────────────────────────────────── */}
      <div
        ref={chartsRef}
        className="min-h-screen bg-white border-t border-gray-100 flex flex-col px-16 py-20"
      >
        <div className="max-w-5xl mx-auto w-full flex flex-col gap-10">
          <div>
            <h2 className="text-xl font-semibold text-black">Compare tasks</h2>
            <p className="text-[11px] text-gray-400 font-light mt-1 italic">
              Select a metric and unit to explore resource use across common AI tasks.
            </p>
          </div>

          {/* Controls */}
          <div className="flex flex-wrap items-center gap-4">
            {/* Metric */}
            <div className="flex rounded-full border border-gray-200 overflow-hidden text-xs">
              {(["energy", "water"] as ChartMetric[]).map((m) => (
                <button
                  key={m}
                  onClick={() => { setChartMetric(m); setChartUnit("raw"); }}
                  className={[
                    "px-5 py-2 transition-colors capitalize",
                    chartMetric === m ? "bg-black text-white" : "text-gray-400 hover:text-black",
                  ].join(" ")}
                >
                  {m}
                </button>
              ))}
            </div>

            {/* Unit */}
            <div className="flex rounded-full border border-gray-200 overflow-hidden text-xs">
              {(["raw", "equiv1", "equiv2"] as ChartUnit[]).map((u) => (
                <button
                  key={u}
                  onClick={() => setChartUnit(u)}
                  className={[
                    "px-4 py-2 transition-colors",
                    chartUnit === u ? "bg-black text-white" : "text-gray-400 hover:text-black",
                  ].join(" ")}
                >
                  {u === "raw"
                    ? chartMetric === "energy" ? "Wh" : "mL"
                    : u === "equiv1"
                    ? chartMetric === "energy" ? "Netflix mins" : "handwashes"
                    : chartMetric === "energy" ? "LED hrs" : "500mL bottles"}
                </button>
              ))}
            </div>

            {/* Exclude training */}
            <label className="flex items-center gap-2 text-[11px] text-gray-400 font-light cursor-pointer select-none">
              <input
                type="checkbox"
                checked={excludeTraining}
                onChange={(e) => setExcludeTraining(e.target.checked)}
                className="w-3 h-3 accent-black"
              />
              exclude "train LLM" (extremely large, skews scale)
            </label>
          </div>

          {/* Bar chart */}
          <div className="w-full h-72">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={chartData} margin={{ top: 8, right: 16, left: 8, bottom: 16 }}>
                <XAxis
                  dataKey="name"
                  tick={{ fontSize: 10, fill: "#9ca3af", fontFamily: "'Jost', sans-serif" }}
                  axisLine={{ stroke: "#e5e7eb" }}
                  tickLine={false}
                />
                <YAxis
                  tick={{ fontSize: 10, fill: "#9ca3af", fontFamily: "'Jost', sans-serif" }}
                  axisLine={false}
                  tickLine={false}
                  tickFormatter={fmtVal}
                  label={{
                    value: unitLabel,
                    angle: -90,
                    position: "insideLeft",
                    offset: 12,
                    style: { fontSize: 10, fill: "#9ca3af", fontFamily: "'Jost', sans-serif" },
                  }}
                  width={55}
                />
                <Tooltip content={<ChartTooltip unitLabel={unitLabel} />} cursor={{ fill: "#f9fafb" }} />
                <Bar dataKey="value" radius={[3, 3, 0, 0]}>
                  {chartData.map((entry) => (
                    <Cell key={entry.id} fill={entry.id === selectedId ? "#000" : "#d1d5db"} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>

          {/* Chart disclaimer */}
          <p className="text-[10px] text-gray-300 italic font-light max-w-3xl leading-relaxed">
            All values are mid-range estimates. Energy in watt-hours (Wh). Water in millilitres (mL). Netflix equivalent at 0.8 Wh/min (HD streaming). LED equivalent at 10W bulb. Handwash at 110 mL. The currently selected scenario is highlighted in black.{" "}
            Data sources: Luccioni et al. 2023, Li et al. 2023, Fernandez et al. 2025, EPRI 2024, Goldman Sachs 2024, Strubell et al. 2019, IEA 2025.
          </p>
        </div>
      </div>

      {/* ─── MODALS ───────────────────────────────────────────────────── */}
      <AnimatePresence>
        {showSources && (
          <Modal onClose={() => setShowSources(false)}>
            <SourcesModal />
          </Modal>
        )}
      </AnimatePresence>

      <AnimatePresence>
        {showGaps && (
          <Modal onClose={() => setShowGaps(false)}>
            <GapsModal />
          </Modal>
        )}
      </AnimatePresence>

      {/* ─── GUILT PANEL ──────────────────────────────────────────────── */}
      <AnimatePresence>
        {showGuilt && (
          <GuiltPanel scenario={scenario} onClose={() => setShowGuilt(false)} />
        )}
      </AnimatePresence>
    </div>
  );
}
