import { Router, type IRouter } from "express";

const router: IRouter = Router();

// All sources are real, published sources with verifiable URLs.
// Data is only included where explicitly stated in these sources.
// No figures are estimated or extrapolated here — only what the source itself claims.
const SOURCES = [
  // ─── 2025–2026 PRIMARY SOURCES ───────────────────────────────────────────
  {
    id: "iea2025",
    title: "Energy and AI",
    authors: ["International Energy Agency"],
    institution: "International Energy Agency (IEA)",
    year: 2025,
    url: "https://www.iea.org/reports/energy-and-ai",
    category: "government",
    methodology: "Aggregated data from national grid operators, utility filings, technology company capacity announcements, and IEA modelling. Built three scenario projections (Base Case, Lift-Off, Headwinds) to 2035 based on AI adoption rates, grid expansion, and efficiency trends.",
    keyFindings: "Global data center electricity demand projected to more than double from ~415 TWh in 2024 to 945 TWh in 2030 (nearly 3% of global electricity). AI is the primary driver. Base case projects ~1,200 TWh by 2035. AI-optimized hyperscale data centers can exceed 100 MW power density. US data centers account for approximately 50% of projected growth.",
    limitations: "AI-specific workloads are not disaggregated from overall data center use. Wide scenario range (700–1,700 TWh by 2035) reflects deep uncertainty. Relies on voluntary disclosures from tech companies. Does not break down energy by AI task type.",
    dataAvailability: "partial",
    avgTrustRating: 4.8,
    totalRatings: 0,
  },
  {
    id: "google2025esr",
    title: "Google 2025 Environmental Report",
    authors: ["Google LLC"],
    institution: "Google / Alphabet Inc.",
    year: 2025,
    url: "https://sustainability.google/reports/google-2025-environmental-report/",
    category: "industry",
    methodology: "Self-reported corporate sustainability data covering FY2024. Includes data center PUE, water usage effectiveness (WUE), and total electricity consumption. Highlights new Trillium (6th-gen) TPU efficiency gains. Third-party audited for select metrics.",
    keyFindings: "Supply chain and total emissions continued to rise despite data center efficiency progress, driven by AI infrastructure expansion. Google's 6th-gen TPU (Trillium) offers improved performance per watt. Total electricity consumption and water use increased year-over-year. Google does not isolate AI-specific energy or water consumption from broader data center operations.",
    limitations: "Company self-reported with potential incentive to present favorably. AI-specific workloads not isolated from other compute. Renewable energy claims use RECs (Renewable Energy Certificates), not necessarily matched hour-by-hour with actual consumption.",
    dataAvailability: "partial",
    avgTrustRating: 3.8,
    totalRatings: 0,
  },
  {
    id: "microsoft2025esr",
    title: "2025 Environmental Sustainability Report",
    authors: ["Microsoft Corporation"],
    institution: "Microsoft Corporation",
    year: 2025,
    url: "https://cdn-dynmedia-1.microsoft.com/is/content/microsoftcorp/microsoft/msc/documents/presentations/CSR/2025-Microsoft-Environmental-Sustainability-Report.pdf",
    category: "industry",
    methodology: "Self-reported corporate ESG data covering FY2024. Includes Scope 1, 2, and 3 emissions. Covers water usage across Azure data center portfolio. New zero-water cooling infrastructure introduced for AI data centers.",
    keyFindings: "Total emissions (Scope 1+2+3) increased 23.4% against a 2020 baseline, primarily driven by AI and cloud expansion. Energy use increased 168% since 2020 baseline. New zero-water cooling designs save ~125,000 m³ of water per facility annually. Microsoft acknowledged moving further from its 2030 carbon-negative goal due to AI infrastructure growth.",
    limitations: "Company self-reported. Does not isolate AI versus other cloud workloads. Conflict of interest as a major AI investor and developer (OpenAI partnership). Scope 3 emissions remain the largest and least controllable category.",
    dataAvailability: "partial",
    avgTrustRating: 3.7,
    totalRatings: 0,
  },
  {
    id: "epri2024",
    title: "Powering Intelligence: Analyzing Artificial Intelligence and Data Center Energy Consumption",
    authors: ["Electric Power Research Institute"],
    institution: "Electric Power Research Institute (EPRI)",
    year: 2024,
    url: "https://www.epri.com/research/products/3002028905",
    category: "industry",
    methodology: "Developed four AI growth scenarios (3.7%–15% annual data center load growth) based on GPU shipment data, hyperscale announcements, and modelled AI workload intensity. A ChatGPT query energy estimate of 2.9 Wh derived from published compute benchmarks and assumed data center PUE.",
    keyFindings: "Data centers consumed ~4% of US electricity in 2023. By 2030, this could reach 4.6%–9.1%. A ChatGPT query uses approximately 2.9 Wh — roughly 10× a traditional Google Search (estimated at 0.3 Wh). 80% of US data center load is concentrated in 15 states, led by Virginia and Texas. Hyperscale centers draw 100–1,000 MW each.",
    limitations: "The ChatGPT 2.9 Wh figure is derived from modeling assumptions, not direct measurement of OpenAI's infrastructure. Growth scenarios span a very wide range, reflecting fundamental uncertainty. Does not cover water use.",
    dataAvailability: "partial",
    avgTrustRating: 4.4,
    totalRatings: 0,
  },
  {
    id: "goldmansachs2024",
    title: "AI is set to drive surging power demand — and here's what that means",
    authors: ["Goldman Sachs Research"],
    institution: "Goldman Sachs",
    year: 2024,
    url: "https://www.goldmansachs.com/insights/articles/ai-to-drive-165-increase-in-data-center-power-demand-by-2030",
    category: "industry",
    methodology: "Goldman Sachs Carbonomics and equity research teams modelled AI-driven data center power demand growth using GPU shipment forecasts, hyperscaler capital expenditure announcements, and utility infrastructure plans.",
    keyFindings: "Predicts a 165% increase in global data center power demand by 2030. US data centers will consume 8% of total US electricity by 2030. AI chatbot queries use ~10× more electricity than traditional web searches. The energy mix for this growth projected at ~60% natural gas and 40% renewables, raising concerns about near-term emissions increases. Additional 215–220 million tonnes of CO₂ projected globally by 2030.",
    limitations: "Analyst projection, not a peer-reviewed study. The 10× search comparison is widely cited but based on estimated figures, not direct measurement. Grid transmission and supply chain constraints may limit actual realization. Published without full methodology disclosure.",
    dataAvailability: "partial",
    avgTrustRating: 3.9,
    totalRatings: 0,
  },
  {
    id: "lbnl2024",
    title: "2024 United States Data Center Energy Usage Report",
    authors: ["Arman Shehabi", "Sarah Josephine Smith", "Eric Masanet", "Jonathan Koomey"],
    institution: "Lawrence Berkeley National Laboratory (LBNL) / US Department of Energy",
    year: 2024,
    url: "https://eta-publications.lbl.gov/sites/default/files/2024-12/lbnl-2024-united-states-data-center-energy-usage-report_1.pdf",
    category: "government",
    methodology: "Compiled historical US data center electricity consumption from 2014–2023 using utility data, survey data, and published hardware efficiency benchmarks. Built scenarios to forecast 2028 demand based on GPU deployment rates and workload shifts toward AI.",
    keyFindings: "US data center electricity use was 176 TWh in 2023 (~4.4% of US electricity). Projected to reach 325–580 TWh (6.7–12% of total US electricity) by 2028, driven primarily by AI GPU workloads. The shift from CPUs to GPUs for AI training and inference is the dominant driver of increased energy intensity per data center. Historical efficiency gains (PUE improvements, hardware) partially offset growth but are now being overwhelmed by scale.",
    limitations: "Historical utility forecasts have often overestimated demand growth, so upper-bound estimates should be treated cautiously. Does not break down by AI task type. Does not cover water consumption. Forecasts assume continued hyperscaler expansion.",
    dataAvailability: "partial",
    avgTrustRating: 4.6,
    totalRatings: 0,
  },
  {
    id: "imf2025",
    title: "Power Hungry: How AI Will Drive Energy Demand",
    authors: ["Christian Bogmans", "Lama Kiyasseh", "Akito Matsumoto", "Andrea Pescatori"],
    institution: "International Monetary Fund (IMF)",
    year: 2025,
    url: "https://www.imf.org/en/publications/wp/issues/2025/04/21/power-hungry-how-ai-will-drive-energy-demand-566304",
    category: "government",
    methodology: "IMF Working Paper using macroeconomic modelling to estimate AI energy demand growth under constrained renewable and unconstrained scenarios. Incorporated grid investment costs, electricity price pass-through effects, and state-level policy data.",
    keyFindings: "Under constrained renewable scenarios, US electricity prices could rise 8.6% due to AI demand growth, with emissions up 5.5%. Seven US states passed laws in 2025 requiring large electricity users (including data centers) to pay grid interconnection infrastructure costs. AI energy demand growth is likely to require significant new electricity generation capacity globally.",
    limitations: "Macroeconomic modelling with many assumptions. Scenario outcomes vary widely. Does not directly measure AI energy use per task. Policy landscape is highly fragmented by jurisdiction.",
    dataAvailability: "partial",
    avgTrustRating: 4.3,
    totalRatings: 0,
  },
  {
    id: "stanfordfmti2025",
    title: "Foundation Model Transparency Index — December 2025",
    authors: ["Percy Liang", "Rishi Bommasani", "et al."],
    institution: "Stanford Center for Research on Foundation Models (CRFM)",
    year: 2025,
    url: "https://crfm.stanford.edu/fmti/",
    category: "academic",
    methodology: "Scored 100 AI foundation models across 100 transparency indicators including compute, energy, water, and data disclosure. Ratings based on publicly available information; companies could also submit self-reported data. Covers major labs including OpenAI, Anthropic, Google, Meta, Mistral.",
    keyFindings: "Most frontier AI companies score poorly on energy and water disclosure transparency. Anthropic disclosed Claude's training energy at approximately 10,000 MWh for a frontier model, with ~5,000 tCO₂ equivalent. OpenAI, Google, and others did not disclose model-specific training energy in this index. The average transparency score remains low, with energy disclosure being one of the weakest categories across all companies.",
    limitations: "Transparency scores reflect disclosure, not actual impact. Companies can improve scores by disclosing without necessarily reducing environmental impact. Self-reported data is not independently verified. Covers only training, not inference.",
    dataAvailability: "partial",
    avgTrustRating: 4.5,
    totalRatings: 0,
  },
  {
    id: "fernandez2025",
    title: "Energy Considerations of Large Language Model Inference and Efficiency Optimizations",
    authors: ["Jared Fernandez", "Clara Na", "Sasha Luccioni", "Emma Strubell", "et al."],
    institution: "Carnegie Mellon University / Hugging Face",
    year: 2025,
    url: "https://aclanthology.org/2025.acl-long.1563.pdf",
    category: "academic",
    methodology: "Directly measured inference energy for LLMs across multiple architectures using hardware performance counters. Analyzed impact of efficiency optimizations (quantization, speculative decoding, batching) on energy use. Published at ACL 2025.",
    keyFindings: "Energy intensity scales sub-linearly with sequence length at small batch sizes. Multi-purpose generative models emit ~10g CO₂eq per 1,000 inferences versus ~0.3g for task-specific models (a 33× difference). Efficiency optimizations like quantization can reduce inference energy by 20–60% without significant accuracy loss. Video generation is exceptionally energy-intensive, with newer large models using ~3.4 million joules per 5-second video clip — approximately 30× more than earlier generation video models.",
    limitations: "Measurements conducted on controlled hardware (A100/H100 GPUs) in research settings, which may differ from production deployments. Does not account for full data center overhead (PUE, networking, storage). Only open-source or accessible models could be measured; GPT-4, Claude, Gemini remain unverifiable.",
    dataAvailability: "full",
    avgTrustRating: 4.7,
    totalRatings: 0,
  },

  // ─── FOUNDATIONAL STUDIES (still primary measurement references) ─────────
  {
    id: "luccioni2023",
    title: "Power Hungry Processing: Watts Driving the Cost of AI Deployment?",
    authors: ["Alexandra Sasha Luccioni", "Yacine Jernite", "Emma Strubell"],
    institution: "Hugging Face / University of Massachusetts Amherst",
    year: 2023,
    url: "https://dl.acm.org/doi/10.1145/3630106.3658542",
    category: "academic",
    methodology: "Directly measured energy consumption of inference (not training) for 88 AI models across text, image, and speech tasks using NVIDIA A100 GPUs and the CodeCarbon tracking library. Standardized per 1,000 inferences. Published at ACM FAccT 2024.",
    keyFindings: "Image generation is 5–133× more energy intensive than text generation per task. Generative tasks are universally more expensive than discriminative (classification) tasks. A single image generation query uses approximately 2.4 Wh. A single text generation query averages approximately 0.3 Wh per 1,000 tokens processed. Large variation between models.",
    limitations: "Inference measured on A100 GPUs in controlled lab setting. Does not account for data center PUE, network, or storage overhead. Only open-source models measured; closed models (GPT-4, Claude, Gemini) could not be directly measured.",
    dataAvailability: "full",
    avgTrustRating: 4.8,
    totalRatings: 0,
  },
  {
    id: "li2023",
    title: "Making AI Less 'Thirsty': Uncovering and Addressing the Secret Water Footprint of AI Models",
    authors: ["Pengfei Li", "Jianyi Yang", "Mohammad A. Islam", "Shaolei Ren"],
    institution: "University of California, Riverside",
    year: 2023,
    url: "https://arxiv.org/abs/2304.03271",
    category: "academic",
    methodology: "Estimated water consumption for cooling data centers by combining water usage effectiveness (WUE) metrics from public disclosures with modelled compute estimates for training/inference. Inference water estimates based on GPT-3-scale model serving assumptions.",
    keyFindings: "GPT-3 training consumed approximately 700,000 liters of fresh water. A 20–50 question conversation with ChatGPT (GPT-3.5/4) requires roughly 500 mL of water. On-site water use from cooling varies significantly by data center location and season.",
    limitations: "Microsoft, Google, and OpenAI did not publicly disclose data center-specific water usage for AI workloads at time of study. All estimates are modelled, not directly measured. Authors contacted companies who did not confirm or deny the figures.",
    dataAvailability: "partial",
    avgTrustRating: 4.2,
    totalRatings: 0,
  },
  {
    id: "strubell2019",
    title: "Energy and Policy Considerations for Deep Learning in NLP",
    authors: ["Emma Strubell", "Ananya Ganesh", "Andrew McCallum"],
    institution: "University of Massachusetts Amherst",
    year: 2019,
    url: "https://arxiv.org/abs/1906.02629",
    category: "academic",
    methodology: "Measured actual power draw using Intel RAPL interface for training NLP models including BERT and NAS. Converted to CO2 using US average grid intensity. The paper that launched widespread attention to AI training's carbon cost.",
    keyFindings: "Training a large NLP model (BERT) produces ~1,438 lbs CO2eq — equivalent to a trans-American flight. Training with neural architecture search cost ~626,155 lbs CO2eq. Called for industry to report training energy costs routinely.",
    limitations: "Only covers training, not inference. Based on 2018-era models and US grid. Does not account for renewable energy use. A foundational study — newer models and infrastructure have changed since publication.",
    dataAvailability: "full",
    avgTrustRating: 4.7,
    totalRatings: 0,
  },
  {
    id: "dodge2022",
    title: "Measuring the Carbon Intensity of AI in Cloud Instances",
    authors: ["Jesse Dodge", "Taylor Prewitt", "Remi Tachet des Combes", "Erika Odmark", "Roy Schwartz", "Emma Strubell", "Alexandra Sasha Luccioni", "Noah A. Smith", "Nicole DeCario", "Will Buchanan"],
    institution: "Allen Institute for AI (AI2)",
    year: 2022,
    url: "https://arxiv.org/abs/2206.05229",
    category: "academic",
    methodology: "Measured actual carbon intensity of AI workloads run on cloud instances across different geographic regions and times of day. Used real-time grid carbon intensity data from the Electricity Map API.",
    keyFindings: "Carbon intensity of the same AI workload can vary by 40× depending on which cloud region it runs in and time of day. Running AI in US West versus US East can produce dramatically different emissions. Time-shifting workloads to off-peak renewable hours is highly effective for reducing carbon footprint.",
    limitations: "Only covers compute-related carbon; does not address water, hardware manufacturing, or network energy. Limited to cloud regions studied. Carbon intensity data from Electricity Map may have inaccuracies.",
    dataAvailability: "full",
    avgTrustRating: 4.6,
    totalRatings: 0,
  },
  // ─── NON-DISCLOSURE DOCUMENTATION ───────────────────────────────────────
  {
    id: "openai-nodisclosure",
    title: "GPT-4 Technical Report",
    authors: ["OpenAI"],
    institution: "OpenAI",
    year: 2023,
    url: "https://arxiv.org/abs/2303.08774",
    category: "industry",
    methodology: "Technical report on GPT-4 capabilities. Provides some compute efficiency context but explicitly declines to disclose training energy, water use, model size, or infrastructure details, citing safety and competitive concerns.",
    keyFindings: "OpenAI confirmed GPT-4 uses a mixture-of-experts architecture. No specific energy, water, or CO2 figures disclosed. OpenAI does not publish a corporate environmental sustainability report as of March 2026. All OpenAI compute runs on Microsoft Azure, meaning energy figures appear in Microsoft's disclosures — not OpenAI's.",
    limitations: "Deliberately omits virtually all environmental impact information. Makes independent verification impossible. This source is cited here specifically to document what OpenAI has NOT disclosed, which is itself an important finding.",
    dataAvailability: "none",
    avgTrustRating: 2.2,
    totalRatings: 0,
  },
];

router.get("/sources", (_req, res) => {
  res.json(SOURCES);
});

export default router;
